[package]
name = "opds_db_api"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
log = "0.4"
env_logger = "0.11"
