[package]
name = "opds_db_api"
version = "1.0.2"
edition = "2021"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
rusqlite = { version = "0.31.0", features = ["collation"]}
log = "0.4"
env_logger = "0.11"
lazy_static = { version = "1.5.0" }